import type { AppMeta } from "./apps";

const v = (
  version: string,
  updated: string,
  changelog: string,
  official: string,
  platforms: string[] = ["Windows", "macOS", "Linux"]
) => ({
  version,
  updatedAt: updated,
  changelog,
  platforms: platforms as ("Windows" | "macOS" | "Linux" | "Android" | "iOS" | "Web" | "Cross-platform")[],
  officialUrl: official,
  cnMirrorUrls: [official],
});

export const APPS_EXTENDED: AppMeta[] = [
  // ----- 办公 -----
  { slug: "notion", name: "Notion", category: "office", description: "一体化笔记、文档与协作工具。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["笔记", "协作"], versions: [v("Notion 2025", "2025-01", "持续更新", "https://www.notion.so")] },
  { slug: "obsidian", name: "Obsidian", category: "office", description: "基于本地 Markdown 的知识库与双链笔记。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["笔记", "Markdown"], versions: [v("Obsidian 1.5", "2025-01", "插件与同步", "https://obsidian.md")] },
  { slug: "typora", name: "Typora", category: "office", description: "所见即所得 Markdown 编辑器。", platforms: ["Windows", "macOS", "Linux"], tags: ["Markdown"], versions: [v("Typora 1.7", "2024-12", "主题与导出", "https://typora.io")] },
  { slug: "libreoffice", name: "LibreOffice", category: "office", description: "开源免费 Office 套件。", platforms: ["Windows", "macOS", "Linux"], tags: ["开源", "文档"], versions: [v("LibreOffice 24.8", "2024-11", "兼容与性能", "https://www.libreoffice.org")] },
  { slug: "onlyoffice", name: "OnlyOffice", category: "office", description: "开源办公套件，支持协作编辑。", platforms: ["Windows", "macOS", "Linux", "Web"], tags: ["开源", "协作"], versions: [v("OnlyOffice 8", "2024-12", "协作与格式", "https://www.onlyoffice.com")] },
  { slug: "google-docs", name: "Google Docs", category: "office", description: "谷歌在线文档、表格与演示。", platforms: ["Web"], tags: ["在线", "协作"], versions: [v("Web", "2025-01", "实时协作", "https://docs.google.com")] },
  { slug: "飞书", name: "飞书", category: "office", description: "字节跳动出品的一站式协作与文档平台。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["协作", "国产"], versions: [v("飞书 2025", "2025-01", "文档与会议", "https://www.feishu.cn")] },
  { slug: "语雀", name: "语雀", category: "office", description: "蚂蚁集团的知识库与文档协作产品。", platforms: ["Web", "Android", "iOS"], tags: ["知识库", "国产"], versions: [v("语雀 Web", "2025-01", "知识库", "https://www.yuque.com")] },
  { slug: "腾讯文档", name: "腾讯文档", category: "office", description: "腾讯出品的在线协作文档。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["协作", "国产"], versions: [v("腾讯文档 2025", "2025-01", "协作与模板", "https://docs.qq.com")] },
  { slug: "drawio", name: "draw.io", category: "office", description: "免费流程图与图表绘制工具。", platforms: ["Web", "Windows", "macOS"], tags: ["流程图", "图表"], versions: [v("draw.io Desktop", "2024-12", "图表与导出", "https://www.diagrams.net")] },
  // ----- 设计 -----
  { slug: "sketch", name: "Sketch", category: "design", description: "macOS 端专业 UI 设计工具。", platforms: ["macOS"], tags: ["UI"], versions: [v("Sketch 100", "2024-12", "协作与插件", "https://www.sketch.com")] },
  { slug: "affinity-designer", name: "Affinity Designer", category: "design", description: "专业矢量与 UI 设计软件，一次购买永久使用。", platforms: ["Windows", "macOS", "iOS"], tags: ["矢量", "UI"], versions: [v("Affinity Designer 2", "2024-11", "性能与格式", "https://affinity.serif.com/designer")] },
  { slug: "blender", name: "Blender", category: "design", description: "开源 3D 创作套件，建模、动画、渲染。", platforms: ["Windows", "macOS", "Linux"], tags: ["3D", "开源"], versions: [v("Blender 4.2", "2024-12", "渲染与模拟", "https://www.blender.org")] },
  { slug: "canva", name: "Canva", category: "design", description: "在线平面设计与模板工具。", platforms: ["Web", "Android", "iOS"], tags: ["模板", "在线"], versions: [v("Canva 2025", "2025-01", "AI 与模板", "https://www.canva.com")] },
  { slug: "adobe-illustrator", name: "Adobe Illustrator", category: "design", description: "行业标准矢量图形软件。", platforms: ["Windows", "macOS"], tags: ["矢量"], versions: [v("Illustrator 2024", "2024-11", "AI 与性能", "https://www.adobe.com/products/illustrator.html")] },
  { slug: "adobe-xd", name: "Adobe XD", category: "design", description: "UX 设计与原型工具（已并入其他 Adobe 产品）。", platforms: ["Windows", "macOS"], tags: ["UX", "原型"], versions: [v("Adobe XD", "2024-06", "设计与共享", "https://www.adobe.com/products/xd.html")] },
  { slug: "principle", name: "Principle", category: "design", description: "Mac 端交互动效与原型工具。", platforms: ["macOS"], tags: ["动效", "原型"], versions: [v("Principle 6", "2024-10", "动效与导出", "https://principleformac.com")] },
  { slug: "lunacy", name: "Lunacy", category: "design", description: "免费 Sket ch 替代品，支持 Windows。", platforms: ["Windows", "macOS", "Linux"], tags: ["UI", "免费"], versions: [v("Lunacy 9", "2024-12", "兼容 .sketch", "https://icons8.com/lunacy")] },
  // ----- 开发 -----
  { slug: "cursor", name: "Cursor", category: "dev", description: "AI 驱动的代码编辑器，基于 VS Code。", platforms: ["Windows", "macOS", "Linux"], tags: ["AI", "编辑器"], versions: [v("Cursor 0.40", "2025-02", "AI 补全与对话", "https://cursor.com")] },
  { slug: "visual-studio", name: "Visual Studio", category: "dev", description: "微软全功能 IDE，.NET 与 C++ 等。", platforms: ["Windows", "macOS"], tags: ["IDE"], versions: [v("VS 2022 17.8", "2024-11", "性能与 C++", "https://visualstudio.microsoft.com")] },
  { slug: "jetbrains-pycharm", name: "PyCharm", category: "dev", description: "JetBrains 出品的 Python IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["Python", "IDE"], versions: [v("PyCharm 2024.3", "2024-12", "AI 与调试", "https://www.jetbrains.com/pycharm")] },
  { slug: "jetbrains-webstorm", name: "WebStorm", category: "dev", description: "JetBrains 前端与 Node 开发 IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["前端", "IDE"], versions: [v("WebStorm 2024.3", "2024-12", "框架支持", "https://www.jetbrains.com/webstorm")] },
  { slug: "sublime-text", name: "Sublime Text", category: "dev", description: "轻量高性能代码编辑器。", platforms: ["Windows", "macOS", "Linux"], tags: ["编辑器"], versions: [v("Sublime Text 4", "2024-10", "性能与主题", "https://www.sublimetext.com")] },
  { slug: "neovim", name: "Neovim", category: "dev", description: "Vim 的现代分支，可扩展。", platforms: ["Windows", "macOS", "Linux"], tags: ["编辑器", "Vim"], versions: [v("Neovim 0.10", "2024-12", "Lua 与 LSP", "https://neovim.io")] },
  { slug: "git", name: "Git", category: "dev", description: "分布式版本控制系统。", platforms: ["Windows", "macOS", "Linux"], tags: ["版本控制"], versions: [v("Git 2.43", "2024-11", "性能与安全", "https://git-scm.com")] },
  { slug: "github-desktop", name: "GitHub Desktop", category: "dev", description: "GitHub 官方桌面客户端。", platforms: ["Windows", "macOS"], tags: ["Git", "GitHub"], versions: [v("GitHub Desktop 3", "2024-12", "协作与 PR", "https://desktop.github.com")] },
  { slug: "docker-desktop", name: "Docker Desktop", category: "dev", description: "本地容器与 Kubernetes 开发环境。", platforms: ["Windows", "macOS"], tags: ["容器", "K8s"], versions: [v("Docker Desktop 4.28", "2024-12", "构建与运行", "https://www.docker.com/products/docker-desktop")] },
  { slug: "postman", name: "Postman", category: "dev", description: "API 开发与测试工具。", platforms: ["Windows", "macOS", "Linux", "Web"], tags: ["API"], versions: [v("Postman 11", "2024-12", "协作与 Mock", "https://www.postman.com")] },
  { slug: "insomnia", name: "Insomnia", category: "dev", description: "开源 API 与 GraphQL 客户端。", platforms: ["Windows", "macOS", "Linux"], tags: ["API", "开源"], versions: [v("Insomnia 2024", "2024-11", "GraphQL", "https://insomnia.rest")] },
  { slug: "wireshark", name: "Wireshark", category: "dev", description: "网络抓包与分析工具。", platforms: ["Windows", "macOS", "Linux"], tags: ["网络", "调试"], versions: [v("Wireshark 4.2", "2024-11", "协议与过滤", "https://www.wireshark.org")] },
  // ----- 娱乐影音 -----
  { slug: "spotify", name: "Spotify", category: "media", description: "流媒体音乐与播客。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["音乐"], versions: [v("Spotify 2025", "2025-01", "推荐与播客", "https://www.spotify.com")] },
  { slug: "foobar2000", name: "foobar2000", category: "media", description: "高音质本地音乐播放器，高度可定制。", platforms: ["Windows", "Android"], tags: ["音乐", "本地"], versions: [v("foobar2000 2.1", "2024-11", "格式与插件", "https://www.foobar2000.org")] },
  { slug: "potplayer", name: "PotPlayer", category: "media", description: "Windows 端全能视频播放器。", platforms: ["Windows"], tags: ["视频", "播放器"], versions: [v("PotPlayer 240831", "2024-08", "解码与字幕", "https://potplayer.daum.net")] },
  { slug: "mpv", name: "mpv", category: "media", description: "开源极简高性能播放器。", platforms: ["Windows", "macOS", "Linux"], tags: ["视频", "开源"], versions: [v("mpv 0.38", "2024-11", "脚本与硬件解码", "https://mpv.io")] },
  { slug: "obs-studio", name: "OBS Studio", category: "media", description: "开源直播与录屏软件。", platforms: ["Windows", "macOS", "Linux"], tags: ["直播", "录屏", "开源"], versions: [v("OBS 30.2", "2024-12", "编码与插件", "https://obsproject.com")] },
  { slug: "discord", name: "Discord", category: "media", description: "游戏与社区语音聊天平台。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["语音", "社区"], versions: [v("Discord 2025", "2025-01", "语音与活动", "https://discord.com")] },
  { slug: "twitch", name: "Twitch", category: "media", description: "游戏与创意直播平台。", platforms: ["Web", "Android", "iOS"], tags: ["直播"], versions: [v("Twitch App", "2025-01", "直播与订阅", "https://www.twitch.tv")] },
  // ----- 游戏 -----
  { slug: "steam", name: "Steam", category: "games", description: "Valve 游戏平台，海量 PC 游戏。", platforms: ["Windows", "macOS", "Linux"], tags: ["游戏", "平台"], versions: [v("Steam Client", "2025-01", "商店与社区", "https://store.steampowered.com")] },
  { slug: "pcl2", name: "PCL2 启动器", category: "games", description: "《我的世界》Java 版多功能启动器，支持模组与整合包。", platforms: ["Windows"], tags: ["游戏", "Minecraft", "国产"], versions: [v("PCL2 2.x", "2024-12", "模组与联机", "https://github.com/Hex-Dragon/PCL2")] },
  { slug: "epic-games", name: "Epic Games Store", category: "games", description: "Epic 游戏商店与免费周周送。", platforms: ["Windows", "macOS"], tags: ["游戏", "平台"], versions: [v("Epic Games Launcher", "2025-01", "商店与库", "https://store.epicgames.com")] },
  // ----- 通讯社交 -----
  { slug: "telegram", name: "Telegram", category: "social", description: "端到端加密即时通讯与频道。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["即时通讯"], versions: [v("Telegram 10", "2025-01", "频道与机器人", "https://telegram.org")] },
  { slug: "slack", name: "Slack", category: "social", description: "企业协作与即时通讯。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["协作"], versions: [v("Slack 2025", "2025-01", "频道与集成", "https://slack.com")] },
  { slug: "钉钉", name: "钉钉", category: "social", description: "阿里巴巴企业协作与考勤。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["企业", "国产"], versions: [v("钉钉 7", "2025-01", "考勤与审批", "https://www.dingtalk.com")] },
  { slug: "qq", name: "QQ", category: "social", description: "腾讯即时通讯与社交。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["即时通讯", "国产"], versions: [v("QQ 9", "2025-01", "群组与空间", "https://im.qq.com")] },
  { slug: "微博", name: "微博", category: "social", description: "新浪微博，中文社交媒体。", platforms: ["Web", "Android", "iOS"], tags: ["社交", "国产"], versions: [v("微博 2025", "2025-01", "热搜与视频", "https://weibo.com")] },
  { slug: "twitter", name: "X (Twitter)", category: "social", description: "社交媒体与短内容。", platforms: ["Web", "Android", "iOS"], tags: ["社交"], versions: [v("X 2025", "2025-01", "时间线与 Spaces", "https://twitter.com")] },
  { slug: "reddit", name: "Reddit", category: "social", description: "社区论坛与讨论。", platforms: ["Web", "Android", "iOS"], tags: ["社区"], versions: [v("Reddit 2025", "2025-01", "子版与投票", "https://www.reddit.com")] },
  { slug: "linkedin", name: "LinkedIn", category: "social", description: "职业社交与招聘。", platforms: ["Web", "Android", "iOS"], tags: ["职业"], versions: [v("LinkedIn 2025", "2025-01", "人脉与职位", "https://www.linkedin.com")] },
  // ----- 系统工具 -----
  { slug: "everything", name: "Everything", category: "system", description: "Windows 极速文件名搜索。", platforms: ["Windows"], tags: ["搜索"], versions: [v("Everything 1.5", "2024-12", "NTFS 索引", "https://www.voidtools.com")] },
  { slug: "bandizip", name: "Bandizip", category: "system", description: "轻量压缩解压，支持多种格式。", platforms: ["Windows", "macOS"], tags: ["压缩"], versions: [v("Bandizip 7", "2024-11", "解压与预览", "https://www.bandisoft.com/bandizip")] },
  { slug: "winrar", name: "WinRAR", category: "system", description: "经典压缩软件，支持 RAR/ZIP。", platforms: ["Windows", "macOS", "Linux"], tags: ["压缩"], versions: [v("WinRAR 7", "2024-11", "加密与恢复", "https://www.winrar.com")] },
  { slug: "ccleaner", name: "CCleaner", category: "system", description: "系统清理与注册表优化。", platforms: ["Windows", "macOS"], tags: ["清理"], versions: [v("CCleaner 6", "2024-12", "清理与健康", "https://www.ccleaner.com")] },
  { slug: "geek-uninstaller", name: "Geek Uninstaller", category: "system", description: "彻底卸载与残留清理。", platforms: ["Windows"], tags: ["卸载"], versions: [v("Geek Uninstaller 1.5", "2024-10", "强制卸载", "https://geekuninstaller.com")] },
  { slug: "process-explorer", name: "Process Explorer", category: "system", description: "微软 Sysinternals 进程与句柄查看。", platforms: ["Windows"], tags: ["系统"], versions: [v("Process Explorer 17", "2024-08", "进程与 DLL", "https://docs.microsoft.com/sysinternals/downloads/process-explorer")] },
  { slug: "hwinfo", name: "HWiNFO", category: "system", description: "硬件信息与传感器监控。", platforms: ["Windows"], tags: ["硬件"], versions: [v("HWiNFO 8", "2024-12", "传感器与日志", "https://www.hwinfo.com")] },
  { slug: "cpu-z", name: "CPU-Z", category: "system", description: "CPU、主板与内存信息。", platforms: ["Windows", "Android"], tags: ["硬件"], versions: [v("CPU-Z 2.09", "2024-11", "硬件识别", "https://www.cpuid.com/softwares/cpu-z.html")] },
  { slug: "rufus", name: "Rufus", category: "system", description: "Windows 启动 U 盘制作。", platforms: ["Windows"], tags: ["启动盘"], versions: [v("Rufus 4.4", "2024-11", "UEFI 与 ISO", "https://rufus.ie")] },
  { slug: "ventoy", name: "Ventoy", category: "system", description: "多 ISO 启动 U 盘工具。", platforms: ["Windows", "Linux"], tags: ["启动盘", "开源"], versions: [v("Ventoy 1.0.96", "2024-12", "多镜像启动", "https://www.ventoy.net")] },
  // ----- 教育学习 -----
  { slug: "duolingo", name: "Duolingo", category: "education", description: "多语言学习与闯关。", platforms: ["Web", "Android", "iOS"], tags: ["语言"], versions: [v("Duolingo 2025", "2025-01", "课程与排行", "https://www.duolingo.com")] },
  { slug: "coursera", name: "Coursera", category: "education", description: "名校在线课程与证书。", platforms: ["Web", "Android", "iOS"], tags: ["课程"], versions: [v("Coursera 2025", "2025-01", "学位与专项", "https://www.coursera.org")] },
  { slug: "khan-academy", name: "Khan Academy", category: "education", description: "免费 K-12 与大学课程。", platforms: ["Web", "Android", "iOS"], tags: ["免费", "课程"], versions: [v("Khan Academy", "2025-01", "数学与科学", "https://www.khanacademy.org")] },
  { slug: "xmind", name: "XMind", category: "education", description: "思维导图与结构图。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["思维导图"], versions: [v("XMind 2024", "2024-12", "导图与演示", "https://www.xmind.net")] },
  { slug: "marginnote", name: "MarginNote", category: "education", description: "PDF 与电子书阅读、批注与脑图。", platforms: ["macOS", "iOS"], tags: ["阅读", "笔记"], versions: [v("MarginNote 3", "2024-11", "PDF 与卡片", "https://www.marginnote.com")] },
  { slug: "zotero", name: "Zotero", category: "education", description: "开源文献管理与引用。", platforms: ["Windows", "macOS", "Linux"], tags: ["文献", "开源"], versions: [v("Zotero 6", "2024-12", "引用与插件", "https://www.zotero.org")] },
  // ----- 生活服务 -----
  { slug: "美团", name: "美团", category: "lifestyle", description: "外卖、到店与酒旅。", platforms: ["Android", "iOS", "Web"], tags: ["外卖", "国产"], versions: [v("美团 2025", "2025-01", "外卖与团购", "https://www.meituan.com")] },
  { slug: "滴滴出行", name: "滴滴出行", category: "lifestyle", description: "网约车与出行。", platforms: ["Android", "iOS", "Web"], tags: ["出行", "国产"], versions: [v("滴滴 2025", "2025-01", "快车与顺风车", "https://www.didiglobal.com")] },
  { slug: "高德地图", name: "高德地图", category: "lifestyle", description: "地图导航与出行。", platforms: ["Android", "iOS", "Web"], tags: ["地图", "国产"], versions: [v("高德 2025", "2025-01", "导航与 POI", "https://www.amap.com")] },
  { slug: "百度地图", name: "百度地图", category: "lifestyle", description: "地图与生活服务。", platforms: ["Android", "iOS", "Web"], tags: ["地图", "国产"], versions: [v("百度地图 2025", "2025-01", "导航与周边", "https://map.baidu.com")] },
  { slug: "12306", name: "铁路 12306", category: "lifestyle", description: "中国铁路官方购票与查询。", platforms: ["Android", "iOS", "Web"], tags: ["出行", "国产"], versions: [v("12306 2025", "2025-01", "购票与候补", "https://www.12306.cn")] },
  { slug: "携程", name: "携程", category: "lifestyle", description: "机票酒店与旅游预订。", platforms: ["Android", "iOS", "Web"], tags: ["旅游", "国产"], versions: [v("携程 2025", "2025-01", "酒店与机票", "https://www.ctrip.com")] },
  { slug: "饿了么", name: "饿了么", category: "lifestyle", description: "外卖与本地生活。", platforms: ["Android", "iOS", "Web"], tags: ["外卖", "国产"], versions: [v("饿了么 2025", "2025-01", "外卖与超市", "https://www.ele.me")] },
  { slug: "闲鱼", name: "闲鱼", category: "lifestyle", description: "阿里旗下二手交易。", platforms: ["Android", "iOS", "Web"], tags: ["二手", "国产"], versions: [v("闲鱼 2025", "2025-01", "闲置与同城", "https://2.taobao.com")] },
];
