/**
 * 生成每类约 200 个应用，输出到 lib/apps-generated.ts
 * 运行: node scripts/generate-apps.js
 */

const fs = require("fs");
const path = require("path");

const PLATFORMS = ["Windows", "macOS", "Linux", "Android", "iOS", "Web", "Cross-platform"];

function ver(version, updated, changelog, url, platforms = ["Windows", "macOS", "Linux"]) {
  return {
    version,
    updatedAt: updated,
    changelog,
    platforms,
    officialUrl: url,
    cnMirrorUrls: [url],
  };
}

// 每类种子应用：尽量真实名称与描述
const SEED = {
  office: [
    { slug: "microsoft-office", name: "Microsoft 365", description: "微软 Office 套件，Word/Excel/PPT。", platforms: ["Windows", "macOS", "Web"], tags: ["文档", "表格"] },
    { slug: "wps-office", name: "WPS Office", description: "金山国产 Office，兼容微软格式。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["国产", "文档"] },
    { slug: "notion", name: "Notion", description: "一体化笔记与协作。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["笔记", "协作"] },
    { slug: "obsidian", name: "Obsidian", description: "双链 Markdown 知识库。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["笔记"] },
    { slug: "typora", name: "Typora", description: "所见即所得 Markdown 编辑器。", platforms: ["Windows", "macOS", "Linux"], tags: ["Markdown"] },
    { slug: "libreoffice", name: "LibreOffice", description: "开源 Office 套件。", platforms: ["Windows", "macOS", "Linux"], tags: ["开源"] },
    { slug: "onlyoffice", name: "OnlyOffice", description: "开源协作办公。", platforms: ["Windows", "macOS", "Linux", "Web"], tags: ["开源", "协作"] },
    { slug: "google-docs", name: "Google Docs", description: "谷歌在线文档。", platforms: ["Web"], tags: ["在线"] },
    { slug: "feishu", name: "飞书", description: "字节协作与文档。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["协作", "国产"] },
    { slug: "yuque", name: "语雀", description: "蚂蚁知识库与文档。", platforms: ["Web", "Android", "iOS"], tags: ["知识库", "国产"] },
    { slug: "tencent-docs", name: "腾讯文档", description: "腾讯在线协作文档。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["协作", "国产"] },
    { slug: "drawio", name: "draw.io", description: "免费流程图与图表。", platforms: ["Web", "Windows", "macOS"], tags: ["流程图"] },
    { slug: "onenote", name: "OneNote", description: "微软数字笔记本。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["笔记"] },
    { slug: "evernote", name: "Evernote", description: "跨平台笔记与剪藏。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["笔记"] },
    { slug: "bear", name: "Bear", description: "优雅的 Markdown 笔记。", platforms: ["macOS", "iOS"], tags: ["笔记"] },
    { slug: "craft", name: "Craft", description: "文档与演示工具。", platforms: ["macOS", "iOS", "Web"], tags: ["文档"] },
    { slug: "roam-research", name: "Roam Research", description: "双向链接笔记。", platforms: ["Web"], tags: ["笔记"] },
    { slug: "logseq", name: "Logseq", description: "大纲与双链知识库。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["开源", "笔记"] },
    { slug: "microsoft-teams", name: "Microsoft Teams", description: "微软团队协作。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["协作"] },
    { slug: "slack", name: "Slack", description: "企业即时通讯。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["协作"] },
    { slug: "confluence", name: "Confluence", description: "Atlassian 团队知识库。", platforms: ["Web"], tags: ["知识库"] },
    { slug: "quip", name: "Quip", description: "Salesforce 协作文档。", platforms: ["Web", "Android", "iOS"], tags: ["协作"] },
    { slug: "coda", name: "Coda", description: "文档与应用合一。", platforms: ["Web"], tags: ["文档"] },
    { slug: "dropbox-paper", name: "Dropbox Paper", description: "Dropbox 协作文档。", platforms: ["Web", "Android", "iOS"], tags: ["协作"] },
    { slug: "zoho-docs", name: "Zoho Docs", description: "Zoho 在线办公。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["文档"] },
    { slug: "石墨文档", name: "石墨文档", description: "国产在线协作文档。", platforms: ["Web", "Android", "iOS"], tags: ["协作", "国产"] },
    { slug: "腾讯会议", name: "腾讯会议", description: "腾讯视频会议。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["会议", "国产"] },
    { slug: "zoom", name: "Zoom", description: "视频会议与网络研讨会。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["会议"] },
    { slug: "xmind", name: "XMind", description: "思维导图软件。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["思维导图"] },
    { slug: "mindmanager", name: "MindManager", description: "思维导图与规划。", platforms: ["Windows", "macOS"], tags: ["思维导图"] },
  ],
  design: [
    { slug: "figma", name: "Figma", description: "云端 UI/UX 设计。", platforms: ["Web", "Windows", "macOS"], tags: ["UI"] },
    { slug: "sketch", name: "Sketch", description: "macOS UI 设计。", platforms: ["macOS"], tags: ["UI"] },
    { slug: "adobe-photoshop", name: "Adobe Photoshop", description: "图像处理标准。", platforms: ["Windows", "macOS"], tags: ["位图"] },
    { slug: "adobe-illustrator", name: "Adobe Illustrator", description: "矢量图形。", platforms: ["Windows", "macOS"], tags: ["矢量"] },
    { slug: "adobe-xd", name: "Adobe XD", description: "UX 设计与原型。", platforms: ["Windows", "macOS"], tags: ["UX"] },
    { slug: "affinity-photo", name: "Affinity Photo", description: "专业修图，一次购买。", platforms: ["Windows", "macOS", "iOS"], tags: ["修图"] },
    { slug: "affinity-designer", name: "Affinity Designer", description: "矢量与 UI 设计。", platforms: ["Windows", "macOS", "iOS"], tags: ["矢量"] },
    { slug: "blender", name: "Blender", description: "开源 3D 创作。", platforms: ["Windows", "macOS", "Linux"], tags: ["3D", "开源"] },
    { slug: "canva", name: "Canva", description: "在线平面设计模板。", platforms: ["Web", "Android", "iOS"], tags: ["模板"] },
    { slug: "lunacy", name: "Lunacy", description: "免费 Sketch 替代。", platforms: ["Windows", "macOS", "Linux"], tags: ["UI"] },
    { slug: "gimp", name: "GIMP", description: "开源图像编辑。", platforms: ["Windows", "macOS", "Linux"], tags: ["开源", "修图"] },
    { slug: "inkscape", name: "Inkscape", description: "开源矢量编辑。", platforms: ["Windows", "macOS", "Linux"], tags: ["开源", "矢量"] },
    { slug: "krita", name: "Krita", description: "开源数字绘画。", platforms: ["Windows", "macOS", "Linux"], tags: ["绘画", "开源"] },
    { slug: "principle", name: "Principle", description: "Mac 交互动效。", platforms: ["macOS"], tags: ["动效"] },
    { slug: "framer", name: "Framer", description: "设计与代码一体化。", platforms: ["Web", "macOS"], tags: ["UI"] },
    { slug: "procreate", name: "Procreate", description: "iPad 绘画应用。", platforms: ["iOS"], tags: ["绘画"] },
    { slug: "clip-studio-paint", name: "Clip Studio Paint", description: "漫画与插画。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["绘画"] },
    { slug: "coreldraw", name: "CorelDRAW", description: "矢量与排版。", platforms: ["Windows", "macOS"], tags: ["矢量"] },
    { slug: "affinity-publisher", name: "Affinity Publisher", description: "排版与出版。", platforms: ["Windows", "macOS"], tags: ["排版"] },
    { slug: "indesign", name: "Adobe InDesign", description: "排版与出版。", platforms: ["Windows", "macOS"], tags: ["排版"] },
    { slug: "after-effects", name: "After Effects", description: "动效与合成。", platforms: ["Windows", "macOS"], tags: ["动效"] },
    { slug: "premiere-pro", name: "Premiere Pro", description: "视频剪辑。", platforms: ["Windows", "macOS"], tags: ["视频"] },
    { slug: "da-vinci-resolve", name: "DaVinci Resolve", description: "调色与剪辑。", platforms: ["Windows", "macOS", "Linux"], tags: ["视频"] },
    { slug: "figma-variable", name: "Figma Variables", description: "设计变量系统。", platforms: ["Web"], tags: ["UI"] },
    { slug: "penpot", name: "Penpot", description: "开源设计协作。", platforms: ["Web"], tags: ["开源", "UI"] },
    { slug: "gravit-designer", name: "Gravit Designer", description: "矢量设计。", platforms: ["Web", "Windows", "macOS", "Linux"], tags: ["矢量"] },
    { slug: "vectr", name: "Vectr", description: "免费矢量图形。", platforms: ["Web", "Windows", "macOS"], tags: ["矢量"] },
    { slug: "photopea", name: "Photopea", description: "在线 PS 替代。", platforms: ["Web"], tags: ["修图"] },
  ],
  dev: [
    { slug: "visual-studio-code", name: "VS Code", description: "微软轻量代码编辑器。", platforms: ["Windows", "macOS", "Linux"], tags: ["编辑器"] },
    { slug: "cursor", name: "Cursor", description: "AI 驱动代码编辑器。", platforms: ["Windows", "macOS", "Linux"], tags: ["AI", "编辑器"] },
    { slug: "visual-studio", name: "Visual Studio", description: "微软全功能 IDE。", platforms: ["Windows", "macOS"], tags: ["IDE"] },
    { slug: "intellij-idea", name: "IntelliJ IDEA", description: "Java/Kotlin IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "pycharm", name: "PyCharm", description: "Python IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "webstorm", name: "WebStorm", description: "前端与 Node IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "sublime-text", name: "Sublime Text", description: "轻量高性能编辑器。", platforms: ["Windows", "macOS", "Linux"], tags: ["编辑器"] },
    { slug: "neovim", name: "Neovim", description: "现代 Vim。", platforms: ["Windows", "macOS", "Linux"], tags: ["编辑器"] },
    { slug: "git", name: "Git", description: "分布式版本控制。", platforms: ["Windows", "macOS", "Linux"], tags: ["版本控制"] },
    { slug: "github-desktop", name: "GitHub Desktop", description: "GitHub 桌面客户端。", platforms: ["Windows", "macOS"], tags: ["Git"] },
    { slug: "docker-desktop", name: "Docker Desktop", description: "本地容器与 K8s。", platforms: ["Windows", "macOS"], tags: ["容器"] },
    { slug: "postman", name: "Postman", description: "API 开发与测试。", platforms: ["Windows", "macOS", "Linux", "Web"], tags: ["API"] },
    { slug: "insomnia", name: "Insomnia", description: "API 与 GraphQL 客户端。", platforms: ["Windows", "macOS", "Linux"], tags: ["API"] },
    { slug: "wireshark", name: "Wireshark", description: "网络抓包分析。", platforms: ["Windows", "macOS", "Linux"], tags: ["网络"] },
    { slug: "phpstorm", name: "PhpStorm", description: "PHP IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "goland", name: "GoLand", description: "Go IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "rider", name: "Rider", description: ".NET 跨平台 IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "clion", name: "CLion", description: "C/C++ IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "rubymine", name: "RubyMine", description: "Ruby/Rails IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "android-studio", name: "Android Studio", description: "Android 开发。", platforms: ["Windows", "macOS", "Linux"], tags: ["移动端"] },
    { slug: "xcode", name: "Xcode", description: "iOS/macOS 开发。", platforms: ["macOS"], tags: ["移动端"] },
    { slug: "eclipse", name: "Eclipse", description: "Java 等 IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "netbeans", name: "Apache NetBeans", description: "多语言 IDE。", platforms: ["Windows", "macOS", "Linux"], tags: ["IDE"] },
    { slug: "vscode-codium", name: "VSCodium", description: "VS Code 无遥测版。", platforms: ["Windows", "macOS", "Linux"], tags: ["编辑器"] },
    { slug: "zed", name: "Zed", description: "高性能多人编辑器。", platforms: ["Windows", "macOS", "Linux"], tags: ["编辑器"] },
    { slug: "gitkraken", name: "GitKraken", description: "Git 图形客户端。", platforms: ["Windows", "macOS", "Linux"], tags: ["Git"] },
    { slug: "sourcetree", name: "Sourcetree", description: "Atlassian Git 客户端。", platforms: ["Windows", "macOS"], tags: ["Git"] },
    { slug: "tableplus", name: "TablePlus", description: "现代数据库客户端。", platforms: ["Windows", "macOS", "Linux"], tags: ["数据库"] },
    { slug: "dbeaver", name: "DBeaver", description: "开源数据库工具。", platforms: ["Windows", "macOS", "Linux"], tags: ["数据库", "开源"] },
    { slug: "robomongo", name: "Robo 3T", description: "MongoDB 客户端。", platforms: ["Windows", "macOS", "Linux"], tags: ["数据库"] },
  ],
  media: [
    { slug: "spotify", name: "Spotify", description: "流媒体音乐。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["音乐"] },
    { slug: "vlc", name: "VLC", description: "万能播放器。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["播放器"] },
    { slug: "potplayer", name: "PotPlayer", description: "Windows 视频播放。", platforms: ["Windows"], tags: ["播放器"] },
    { slug: "foobar2000", name: "foobar2000", description: "高音质本地音乐。", platforms: ["Windows", "Android"], tags: ["音乐"] },
    { slug: "obs-studio", name: "OBS Studio", description: "开源直播录屏。", platforms: ["Windows", "macOS", "Linux"], tags: ["直播", "开源"] },
    { slug: "discord", name: "Discord", description: "游戏与社区语音。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["语音"] },
    { slug: "twitch", name: "Twitch", description: "游戏直播。", platforms: ["Web", "Android", "iOS"], tags: ["直播"] },
    { slug: "mpv", name: "mpv", description: "极简高性能播放器。", platforms: ["Windows", "macOS", "Linux"], tags: ["播放器", "开源"] },
    { slug: "itunes", name: "Apple Music / iTunes", description: "苹果音乐与媒体库。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["音乐"] },
    { slug: "netflix", name: "Netflix", description: "流媒体视频。", platforms: ["Web", "Android", "iOS"], tags: ["视频"] },
    { slug: "youtube", name: "YouTube", description: "视频分享与观看。", platforms: ["Web", "Android", "iOS"], tags: ["视频"] },
    { slug: "bilibili", name: "哔哩哔哩", description: "弹幕视频与直播。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["视频", "国产"] },
    { slug: "qq-music", name: "QQ 音乐", description: "腾讯音乐。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["音乐", "国产"] },
    { slug: "netease-music", name: "网易云音乐", description: "网易音乐。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["音乐", "国产"] },
    { slug: "kodi", name: "Kodi", description: "家庭影院媒体中心。", platforms: ["Windows", "macOS", "Linux", "Android"], tags: ["媒体中心"] },
    { slug: "jellyfin", name: "Jellyfin", description: "开源媒体服务器。", platforms: ["Windows", "macOS", "Linux"], tags: ["媒体", "开源"] },
    { slug: "plex", name: "Plex", description: "媒体服务器与流媒体。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["媒体"] },
    { slug: "handbrake", name: "HandBrake", description: "开源视频转码。", platforms: ["Windows", "macOS", "Linux"], tags: ["视频", "开源"] },
    { slug: "audacity", name: "Audacity", description: "开源音频编辑。", platforms: ["Windows", "macOS", "Linux"], tags: ["音频", "开源"] },
    { slug: "streamlabs", name: "Streamlabs", description: "直播推流与工具。", platforms: ["Windows", "macOS"], tags: ["直播"] },
    { slug: "musicbee", name: "MusicBee", description: "Windows 本地音乐管理。", platforms: ["Windows"], tags: ["音乐"] },
    { slug: "aimp", name: "AIMP", description: "音频播放器。", platforms: ["Windows", "Android"], tags: ["音乐"] },
    { slug: "disney-plus", name: "Disney+", description: "迪士尼流媒体。", platforms: ["Web", "Android", "iOS"], tags: ["视频"] },
    { slug: "amazon-music", name: "Amazon Music", description: "亚马逊音乐。", platforms: ["Web", "Android", "iOS"], tags: ["音乐"] },
    { slug: "soundcloud", name: "SoundCloud", description: "独立音乐与播客。", platforms: ["Web", "Android", "iOS"], tags: ["音乐"] },
    { slug: "tidal", name: "Tidal", description: "高解析度音乐。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["音乐"] },
    { slug: "youtube-music", name: "YouTube Music", description: "YouTube 音乐。", platforms: ["Web", "Android", "iOS"], tags: ["音乐"] },
    { slug: "kugou", name: "酷狗音乐", description: "酷狗音乐。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["音乐", "国产"] },
    { slug: "kuwo", name: "酷我音乐", description: "酷我音乐。", platforms: ["Windows", "Android", "iOS"], tags: ["音乐", "国产"] },
  ],
  games: [
    { slug: "steam", name: "Steam", description: "Valve PC 游戏平台。", platforms: ["Windows", "macOS", "Linux"], tags: ["平台"] },
    { slug: "pcl2", name: "PCL2 启动器", description: "我的世界 Java 启动器。", platforms: ["Windows"], tags: ["启动器", "国产"] },
    { slug: "epic-games", name: "Epic Games Store", description: "Epic 游戏商店。", platforms: ["Windows", "macOS"], tags: ["平台"] },
    { slug: "gog-galaxy", name: "GOG Galaxy", description: "GOG 游戏平台。", platforms: ["Windows", "macOS"], tags: ["平台"] },
    { slug: "origin", name: "EA App (Origin)", description: "EA 游戏平台。", platforms: ["Windows", "macOS"], tags: ["平台"] },
    { slug: "ubisoft-connect", name: "Ubisoft Connect", description: "育碧游戏平台。", platforms: ["Windows", "macOS"], tags: ["平台"] },
    { slug: "battle-net", name: "Battle.net", description: "暴雪游戏平台。", platforms: ["Windows", "macOS"], tags: ["平台"] },
    { slug: "xbox-app", name: "Xbox App", description: "微软游戏与订阅。", platforms: ["Windows"], tags: ["平台"] },
    { slug: "hmcl", name: "HMCL", description: "我的世界启动器。", platforms: ["Windows", "macOS", "Linux"], tags: ["启动器", "国产"] },
    { slug: "prism-launcher", name: "Prism Launcher", description: "MC 多实例启动器。", platforms: ["Windows", "macOS", "Linux"], tags: ["启动器", "开源"] },
    { slug: "baldurs-gate-3", name: "Baldur's Gate 3", description: "拉瑞安 CRPG 大作。", platforms: ["Windows", "macOS"], tags: ["RPG"] },
    { slug: "elden-ring", name: "Elden Ring", description: "FromSoftware 开放世界魂系。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作", "RPG"] },
    { slug: "disco-elysium", name: "Disco Elysium", description: "文字驱动 RPG。", platforms: ["Windows", "macOS", "Linux"], tags: ["RPG"] },
    { slug: "minecraft", name: "Minecraft", description: "沙盒建造与生存。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["沙盒"] },
    { slug: "cyberpunk-2077", name: "Cyberpunk 2077", description: "赛博朋克开放世界 RPG。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["RPG"] },
    { slug: "the-witcher-3", name: "The Witcher 3", description: "巫师 3 开放世界 RPG。", platforms: ["Windows", "macOS", "Linux", "Switch"], tags: ["RPG"] },
    { slug: "half-life-2", name: "Half-Life 2", description: "Valve 经典 FPS。", platforms: ["Windows", "macOS", "Linux"], tags: ["FPS"] },
    { slug: "portal-2", name: "Portal 2", description: "Valve 解谜。", platforms: ["Windows", "macOS", "Linux"], tags: ["解谜"] },
    { slug: "cs2", name: "Counter-Strike 2", description: "Valve 竞技 FPS。", platforms: ["Windows", "macOS", "Linux"], tags: ["FPS"] },
    { slug: "dota-2", name: "Dota 2", description: "Valve MOBA。", platforms: ["Windows", "macOS", "Linux"], tags: ["MOBA"] },
    { slug: "gta-v", name: "Grand Theft Auto V", description: "开放世界动作。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["开放世界"] },
    { slug: "red-dead-redemption-2", name: "Red Dead Redemption 2", description: "西部开放世界。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["开放世界"] },
    { slug: "hades", name: "Hades", description: "Roguelike 动作。", platforms: ["Windows", "macOS", "Switch"], tags: ["Roguelike"] },
    { slug: "stardew-valley", name: "Stardew Valley", description: "像素农场模拟。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["模拟"] },
    { slug: "terraria", name: "Terraria", description: "2D 沙盒冒险。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["沙盒"] },
    { slug: "hollow-knight", name: "Hollow Knight", description: "类银河战士恶魔城。", platforms: ["Windows", "macOS", "Linux", "Switch"], tags: ["横版"] },
    { slug: "celeste", name: "Celeste", description: "像素平台跳跃。", platforms: ["Windows", "macOS", "Linux", "Switch"], tags: ["平台"] },
    { slug: "slay-the-spire", name: "Slay the Spire", description: "卡牌 Roguelike。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["卡牌"] },
    { slug: "factorio", name: "Factorio", description: "流水线建造策略。", platforms: ["Windows", "macOS", "Linux"], tags: ["策略"] },
    { slug: "civilization-6", name: "Sid Meier's Civilization VI", description: "回合制策略。", platforms: ["Windows", "macOS", "Linux"], tags: ["策略"] },
    { slug: "xcom-2", name: "XCOM 2", description: "回合制战术。", platforms: ["Windows", "macOS", "Linux"], tags: ["策略"] },
    { slug: "total-war-three-kingdoms", name: "Total War: Three Kingdoms", description: "全战三国。", platforms: ["Windows", "macOS"], tags: ["策略"] },
    { slug: "league-of-legends", name: "League of Legends", description: "拳头 MOBA。", platforms: ["Windows", "macOS"], tags: ["MOBA"] },
    { slug: "valorant", name: "Valorant", description: "拳头战术 FPS。", platforms: ["Windows"], tags: ["FPS"] },
    { slug: "overwatch-2", name: "Overwatch 2", description: "暴雪团队射击。", platforms: ["Windows", "macOS", "PlayStation", "Xbox"], tags: ["FPS"] },
    { slug: "world-of-warcraft", name: "World of Warcraft", description: "暴雪 MMORPG。", platforms: ["Windows", "macOS"], tags: ["MMO"] },
    { slug: "diablo-4", name: "Diablo IV", description: "暴雪 ARPG。", platforms: ["Windows", "macOS", "PlayStation", "Xbox"], tags: ["ARPG"] },
    { slug: "hearthstone", name: "Hearthstone", description: "暴雪卡牌。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["卡牌"] },
    { slug: "starcraft-2", name: "StarCraft II", description: "暴雪 RTS。", platforms: ["Windows", "macOS"], tags: ["RTS"] },
    { slug: "fortnite", name: "Fortnite", description: "Epic 大逃杀。", platforms: ["Windows", "macOS", "PlayStation", "Xbox"], tags: ["大逃杀"] },
    { slug: "apex-legends", name: "Apex Legends", description: "Respawn 大逃杀。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["大逃杀"] },
    { slug: "pubg", name: "PUBG: Battlegrounds", description: "大逃杀。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["大逃杀"] },
    { slug: "rocket-league", name: "Rocket League", description: "足球赛车。", platforms: ["Windows", "macOS", "PlayStation", "Xbox"], tags: ["竞技"] },
    { slug: "fifa-ea-sports-fc", name: "EA Sports FC", description: "足球模拟。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["体育"] },
    { slug: "f1-23", name: "F1 23", description: "F1 赛车。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["赛车"] },
    { slug: "forza-horizon-5", name: "Forza Horizon 5", description: "开放世界赛车。", platforms: ["Windows", "Xbox"], tags: ["赛车"] },
    { slug: "assassins-creed-valhalla", name: "Assassin's Creed Valhalla", description: "育碧开放世界。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "far-cry-6", name: "Far Cry 6", description: "育碧开放世界 FPS。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["FPS"] },
    { slug: "rainbow-six-siege", name: "Rainbow Six Siege", description: "育碧战术 FPS。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["FPS"] },
    { slug: "resident-evil-4-remake", name: "Resident Evil 4 Remake", description: "卡普空恐怖动作。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "monster-hunter-world", name: "Monster Hunter: World", description: "卡普空共斗。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "dark-souls-3", name: "Dark Souls III", description: "FromSoftware 魂系。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "sekiro", name: "Sekiro: Shadows Die Twice", description: "FromSoftware 动作。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "bloodborne", name: "Bloodborne", description: "FromSoftware 魂系。", platforms: ["PlayStation"], tags: ["动作"] },
    { slug: "god-of-war", name: "God of War", description: "索尼动作冒险。", platforms: ["Windows", "PlayStation"], tags: ["动作"] },
    { slug: "spider-man-remastered", name: "Marvel's Spider-Man Remastered", description: "漫威开放世界。", platforms: ["Windows", "PlayStation"], tags: ["动作"] },
    { slug: "horizon-zero-dawn", name: "Horizon Zero Dawn", description: "机械兽开放世界。", platforms: ["Windows", "PlayStation"], tags: ["RPG"] },
    { slug: "death-stranding", name: "Death Stranding", description: "小岛秀夫冒险。", platforms: ["Windows", "PlayStation"], tags: ["冒险"] },
    { slug: "final-fantasy-7-remake", name: "Final Fantasy VII Remake", description: "SE RPG。", platforms: ["Windows", "PlayStation"], tags: ["RPG"] },
    { slug: "final-fantasy-14", name: "Final Fantasy XIV", description: "SE MMORPG。", platforms: ["Windows", "macOS", "PlayStation"], tags: ["MMO"] },
    { slug: "nier-automata", name: "NieR: Automata", description: "横尾太郎动作 RPG。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["RPG"] },
    { slug: "persona-5-royal", name: "Persona 5 Royal", description: "Atlus JRPG。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["RPG"] },
    { slug: "yakuza-like-a-dragon", name: "Like a Dragon", description: "如龙 RPG。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["RPG"] },
    { slug: "dragon-quest-11", name: "Dragon Quest XI", description: "勇者斗恶龙。", platforms: ["Windows", "PlayStation", "Switch"], tags: ["RPG"] },
    { slug: "octopath-traveler-2", name: "Octopath Traveler II", description: "HD-2D RPG。", platforms: ["Windows", "PlayStation", "Switch"], tags: ["RPG"] },
    { slug: "sea-of-stars", name: "Sea of Stars", description: "像素 RPG。", platforms: ["Windows", "PlayStation", "Xbox", "Switch"], tags: ["RPG"] },
    { slug: "chained-echoes", name: "Chained Echoes", description: "像素 RPG。", platforms: ["Windows", "PlayStation", "Xbox", "Switch"], tags: ["RPG"] },
    { slug: "dead-cells", name: "Dead Cells", description: "Roguelike 横版。", platforms: ["Windows", "macOS", "Linux", "Switch"], tags: ["Roguelike"] },
    { slug: "vampire-survivors", name: "Vampire Survivors", description: "Roguelike 割草。", platforms: ["Windows", "Android", "iOS", "Xbox"], tags: ["Roguelike"] },
    { slug: "risk-of-rain-2", name: "Risk of Rain 2", description: "Roguelike 合作。", platforms: ["Windows", "macOS", "Linux", "Switch"], tags: ["Roguelike"] },
    { slug: "binding-of-isaac", name: "The Binding of Isaac: Rebirth", description: "Roguelike 地牢。", platforms: ["Windows", "macOS", "Linux", "Switch"], tags: ["Roguelike"] },
    { slug: "inscryption", name: "Inscryption", description: "卡牌与密室逃脱。", platforms: ["Windows", "macOS", "Linux"], tags: ["卡牌"] },
    { slug: "subnautica", name: "Subnautica", description: "海底生存。", platforms: ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], tags: ["生存"] },
    { slug: "valheim", name: "Valheim", description: "维京生存建造。", platforms: ["Windows", "macOS", "Linux"], tags: ["生存"] },
    { slug: "palworld", name: "Palworld", description: "宝可梦风格生存。", platforms: ["Windows", "Xbox"], tags: ["生存"] },
    { slug: "satisfactory", name: "Satisfactory", description: "3D 流水线建造。", platforms: ["Windows", "macOS", "Linux"], tags: ["建造"] },
    { slug: "dyson-sphere-program", name: "Dyson Sphere Program", description: "科幻流水线。", platforms: ["Windows"], tags: ["建造"] },
    { slug: "rimworld", name: "RimWorld", description: "殖民模拟。", platforms: ["Windows", "macOS", "Linux"], tags: ["模拟"] },
    { slug: "crusader-kings-3", name: "Crusader Kings III", description: "P社大战略。", platforms: ["Windows", "macOS", "Linux"], tags: ["策略"] },
    { slug: "stellaris", name: "Stellaris", description: "P社太空 4X。", platforms: ["Windows", "macOS", "Linux"], tags: ["策略"] },
    { slug: "europa-universalis-4", name: "Europa Universalis IV", description: "P社历史策略。", platforms: ["Windows", "macOS", "Linux"], tags: ["策略"] },
    { slug: "hearts-of-iron-4", name: "Hearts of Iron IV", description: "P社二战策略。", platforms: ["Windows", "macOS", "Linux"], tags: ["策略"] },
    { slug: "age-of-empires-4", name: "Age of Empires IV", description: "微软 RTS。", platforms: ["Windows"], tags: ["RTS"] },
    { slug: "star-craft-remastered", name: "StarCraft: Remastered", description: "暴雪 RTS 重制。", platforms: ["Windows", "macOS"], tags: ["RTS"] },
    { slug: "warcraft-3-reforged", name: "Warcraft III: Reforged", description: "暴雪 RTS。", platforms: ["Windows", "macOS"], tags: ["RTS"] },
    { slug: "dota-underlords", name: "Dota Underlords", description: "自走棋。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["自走棋"] },
    { slug: "teamfight-tactics", name: "Teamfight Tactics", description: "拳头自走棋。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["自走棋"] },
    { slug: "gears-5", name: "Gears 5", description: "微软第三人称射击。", platforms: ["Windows", "Xbox"], tags: ["射击"] },
    { slug: "halo-infinite", name: "Halo Infinite", description: "微软 FPS。", platforms: ["Windows", "Xbox"], tags: ["FPS"] },
    { slug: "doom-eternal", name: "Doom Eternal", description: "id 快节奏 FPS。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["FPS"] },
    { slug: "bioshock-infinite", name: "BioShock Infinite", description: "叙事 FPS。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["FPS"] },
    { slug: "metro-exodus", name: "Metro Exodus", description: "末世 FPS。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["FPS"] },
    { slug: "destiny-2", name: "Destiny 2", description: "Bungie 在线射击。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["FPS"] },
    { slug: "warframe", name: "Warframe", description: "免费科幻 TPS。", platforms: ["Windows", "PlayStation", "Xbox", "Switch"], tags: ["射击"] },
    { slug: "path-of-exile", name: "Path of Exile", description: "免费 ARPG。", platforms: ["Windows", "macOS", "PlayStation", "Xbox"], tags: ["ARPG"] },
    { slug: "grim-dawn", name: "Grim Dawn", description: "暗黑风 ARPG。", platforms: ["Windows", "macOS"], tags: ["ARPG"] },
    { slug: "last-epoch", name: "Last Epoch", description: "ARPG。", platforms: ["Windows", "macOS", "Linux"], tags: ["ARPG"] },
    { slug: "lost-ark", name: "Lost Ark", description: "MMOARPG。", platforms: ["Windows"], tags: ["MMO"] },
    { slug: "genshin-impact", name: "原神", description: "米哈游开放世界。", platforms: ["Windows", "PlayStation", "Android", "iOS"], tags: ["RPG", "国产"] },
    { slug: "honkai-star-rail", name: "崩坏：星穹铁道", description: "米哈游回合制。", platforms: ["Windows", "PlayStation", "Android", "iOS"], tags: ["RPG", "国产"] },
    { slug: "reverse-1999", name: "重返未来：1999", description: "回合制卡牌。", platforms: ["Windows", "Android", "iOS"], tags: ["卡牌", "国产"] },
    { slug: "honor-of-kings", name: "王者荣耀", description: "腾讯 MOBA。", platforms: ["Android", "iOS"], tags: ["MOBA", "国产"] },
    { slug: "peacekeeper-elite", name: "和平精英", description: "腾讯大逃杀。", platforms: ["Android", "iOS"], tags: ["大逃杀", "国产"] },
    { slug: "dungeon-fighter-online", name: "地下城与勇士", description: "横版动作。", platforms: ["Windows"], tags: ["动作", "国产"] },
    { slug: "naraka-bladepoint", name: "永劫无间", description: "武侠大逃杀。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作", "国产"] },
    { slug: "sifu", name: "Sifu", description: "功夫动作。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "lies-of-p", name: "Lies of P", description: "魂系动作。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "lords-of-the-fallen", name: "Lords of the Fallen", description: "魂系动作。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["动作"] },
    { slug: "starfield", name: "Starfield", description: "B社太空 RPG。", platforms: ["Windows", "Xbox"], tags: ["RPG"] },
    { slug: "skyrim", name: "The Elder Scrolls V: Skyrim", description: "B社开放世界。", platforms: ["Windows", "PlayStation", "Xbox", "Switch"], tags: ["RPG"] },
    { slug: "fallout-4", name: "Fallout 4", description: "B社末世 RPG。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["RPG"] },
    { slug: "mass-effect-legendary", name: "Mass Effect Legendary Edition", description: "BioWare 科幻 RPG。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["RPG"] },
    { slug: "dragon-age-inquisition", name: "Dragon Age: Inquisition", description: "BioWare 奇幻 RPG。", platforms: ["Windows", "PlayStation", "Xbox"], tags: ["RPG"] },
    { slug: "divinity-original-sin-2", name: "Divinity: Original Sin 2", description: "拉瑞安 CRPG。", platforms: ["Windows", "macOS", "Linux"], tags: ["RPG"] },
  ],
  social: [
    { slug: "wechat", name: "微信", description: "腾讯即时通讯。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["即时通讯", "国产"] },
    { slug: "qq", name: "QQ", description: "腾讯社交。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["即时通讯", "国产"] },
    { slug: "telegram", name: "Telegram", description: "端到端加密通讯。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["即时通讯"] },
    { slug: "slack", name: "Slack", description: "企业协作。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS", "Web"], tags: ["协作"] },
    { slug: "dingtalk", name: "钉钉", description: "阿里企业协作。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["企业", "国产"] },
    { slug: "weibo", name: "微博", description: "新浪社交媒体。", platforms: ["Web", "Android", "iOS"], tags: ["社交", "国产"] },
    { slug: "twitter", name: "X (Twitter)", description: "社交媒体。", platforms: ["Web", "Android", "iOS"], tags: ["社交"] },
    { slug: "reddit", name: "Reddit", description: "社区论坛。", platforms: ["Web", "Android", "iOS"], tags: ["社区"] },
    { slug: "linkedin", name: "LinkedIn", description: "职业社交。", platforms: ["Web", "Android", "iOS"], tags: ["职业"] },
    { slug: "whatsapp", name: "WhatsApp", description: "即时通讯。", platforms: ["Windows", "macOS", "Android", "iOS", "Web"], tags: ["即时通讯"] },
    { slug: "signal", name: "Signal", description: "隐私通讯。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["即时通讯"] },
    { slug: "line", name: "LINE", description: "日本流行通讯。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["即时通讯"] },
    { slug: "viber", name: "Viber", description: "语音与消息。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["即时通讯"] },
    { slug: "mastodon", name: "Mastodon", description: "去中心化社交。", platforms: ["Web", "Android", "iOS"], tags: ["社交", "开源"] },
    { slug: "bluesky", name: "Bluesky", description: "去中心化微博。", platforms: ["Web", "Android", "iOS"], tags: ["社交"] },
    { slug: "threads", name: "Threads", description: "Meta 文字社交。", platforms: ["Android", "iOS", "Web"], tags: ["社交"] },
    { slug: "instagram", name: "Instagram", description: "图片与短视频。", platforms: ["Android", "iOS", "Web"], tags: ["社交"] },
    { slug: "tiktok", name: "TikTok", description: "短视频。", platforms: ["Android", "iOS", "Web"], tags: ["短视频"] },
    { slug: "douyin", name: "抖音", description: "短视频。", platforms: ["Android", "iOS", "Web"], tags: ["短视频", "国产"] },
    { slug: "xiaohongshu", name: "小红书", description: "生活分享与种草。", platforms: ["Android", "iOS", "Web"], tags: ["社交", "国产"] },
    { slug: "zhihu", name: "知乎", description: "问答与社区。", platforms: ["Web", "Android", "iOS"], tags: ["社区", "国产"] },
    { slug: "douban", name: "豆瓣", description: "书影音与小组。", platforms: ["Web", "Android", "iOS"], tags: ["社区", "国产"] },
    { slug: "tieba", name: "百度贴吧", description: "兴趣社区。", platforms: ["Web", "Android", "iOS"], tags: ["社区", "国产"] },
    { slug: "matrix-element", name: "Element", description: "Matrix 去中心化聊天。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["即时通讯", "开源"] },
    { slug: "zulip", name: "Zulip", description: "开源团队聊天。", platforms: ["Web", "Windows", "macOS", "Linux", "Android", "iOS"], tags: ["协作", "开源"] },
    { slug: "mattermost", name: "Mattermost", description: "开源 Slack 替代。", platforms: ["Web", "Windows", "macOS", "Linux", "Android", "iOS"], tags: ["协作", "开源"] },
  ],
  system: [
    { slug: "7zip", name: "7-Zip", description: "开源压缩解压。", platforms: ["Windows"], tags: ["压缩", "开源"] },
    { slug: "everything", name: "Everything", description: "Windows 极速搜索。", platforms: ["Windows"], tags: ["搜索"] },
    { slug: "bandizip", name: "Bandizip", description: "轻量压缩。", platforms: ["Windows", "macOS"], tags: ["压缩"] },
    { slug: "winrar", name: "WinRAR", description: "RAR/ZIP 压缩。", platforms: ["Windows", "macOS", "Linux"], tags: ["压缩"] },
    { slug: "ccleaner", name: "CCleaner", description: "系统清理。", platforms: ["Windows", "macOS"], tags: ["清理"] },
    { slug: "geek-uninstaller", name: "Geek Uninstaller", description: "彻底卸载。", platforms: ["Windows"], tags: ["卸载"] },
    { slug: "process-explorer", name: "Process Explorer", description: "进程与句柄查看。", platforms: ["Windows"], tags: ["系统"] },
    { slug: "hwinfo", name: "HWiNFO", description: "硬件信息监控。", platforms: ["Windows"], tags: ["硬件"] },
    { slug: "cpu-z", name: "CPU-Z", description: "CPU 与主板信息。", platforms: ["Windows", "Android"], tags: ["硬件"] },
    { slug: "rufus", name: "Rufus", description: "启动 U 盘制作。", platforms: ["Windows"], tags: ["启动盘"] },
    { slug: "ventoy", name: "Ventoy", description: "多 ISO 启动 U 盘。", platforms: ["Windows", "Linux"], tags: ["启动盘", "开源"] },
    { slug: "listary", name: "Listary", description: "文件与搜索启动器。", platforms: ["Windows"], tags: ["搜索"] },
    { slug: "wox", name: "Wox", description: "Windows 启动器。", platforms: ["Windows"], tags: ["启动器"] },
    { slug: "powertoys", name: "PowerToys", description: "微软效率工具集。", platforms: ["Windows"], tags: ["效率"] },
    { slug: "sharex", name: "ShareX", description: "截图与分享。", platforms: ["Windows"], tags: ["截图"] },
    { slug: "snipaste", name: "Snipaste", description: "截图与贴图。", platforms: ["Windows", "macOS"], tags: ["截图", "国产"] },
    { slug: "dism-plus", name: "DISM++", description: "系统优化与清理。", platforms: ["Windows"], tags: ["系统", "国产"] },
    { slug: "tree-size", name: "TreeSize", description: "磁盘空间分析。", platforms: ["Windows"], tags: ["磁盘"] },
    { slug: "spacesniffer", name: "SpaceSniffer", description: "磁盘占用可视化。", platforms: ["Windows"], tags: ["磁盘"] },
    { slug: "balena-etcher", name: "Balena Etcher", description: "镜像刻录 U 盘。", platforms: ["Windows", "macOS", "Linux"], tags: ["启动盘"] },
    { slug: "autoruns", name: "Autoruns", description: "启动项管理。", platforms: ["Windows"], tags: ["系统"] },
    { slug: "revo-uninstaller", name: "Revo Uninstaller", description: "深度卸载。", platforms: ["Windows"], tags: ["卸载"] },
    { slug: "glary-utilities", name: "Glary Utilities", description: "系统优化套件。", platforms: ["Windows"], tags: ["优化"] },
    { slug: "advanced-systemcare", name: "Advanced SystemCare", description: "IObit 系统优化。", platforms: ["Windows"], tags: ["优化"] },
    { slug: "macs-fan-control", name: "Macs Fan Control", description: "Mac 风扇控制。", platforms: ["Windows", "macOS"], tags: ["硬件"] },
    { slug: "monitorian", name: "Monitorian", description: "多显示器亮度。", platforms: ["Windows"], tags: ["显示器"] },
    { slug: "flux", name: "f.lux", description: "护眼色温调节。", platforms: ["Windows", "macOS", "Linux", "iOS"], tags: ["护眼"] },
  ],
  education: [
    { slug: "anki", name: "Anki", description: "间隔重复记忆。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["记忆", "开源"] },
    { slug: "duolingo", name: "Duolingo", description: "多语言学习。", platforms: ["Web", "Android", "iOS"], tags: ["语言"] },
    { slug: "coursera", name: "Coursera", description: "名校在线课程。", platforms: ["Web", "Android", "iOS"], tags: ["课程"] },
    { slug: "khan-academy", name: "Khan Academy", description: "免费 K-12 课程。", platforms: ["Web", "Android", "iOS"], tags: ["课程", "免费"] },
    { slug: "xmind", name: "XMind", description: "思维导图。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["思维导图"] },
    { slug: "zotero", name: "Zotero", description: "文献管理与引用。", platforms: ["Windows", "macOS", "Linux"], tags: ["文献", "开源"] },
    { slug: "marginnote", name: "MarginNote", description: "PDF 阅读与脑图。", platforms: ["macOS", "iOS"], tags: ["阅读"] },
    { slug: "notability", name: "Notability", description: "手写笔记与录音。", platforms: ["macOS", "iOS"], tags: ["笔记"] },
    { slug: "goodnotes", name: "GoodNotes", description: "手写笔记与 PDF。", platforms: ["macOS", "iOS"], tags: ["笔记"] },
    { slug: "quizlet", name: "Quizlet", description: "闪卡与学习集。", platforms: ["Web", "Android", "iOS"], tags: ["记忆"] },
    { slug: "memrise", name: "Memrise", description: "语言与词汇。", platforms: ["Web", "Android", "iOS"], tags: ["语言"] },
    { slug: "rosetta-stone", name: "Rosetta Stone", description: "语言学习。", platforms: ["Windows", "macOS", "Android", "iOS"], tags: ["语言"] },
    { slug: "brilliant", name: "Brilliant", description: "数学与科学互动学习。", platforms: ["Web", "Android", "iOS"], tags: ["数学"] },
    { slug: "edx", name: "edX", description: "大学在线课程。", platforms: ["Web", "Android", "iOS"], tags: ["课程"] },
    { slug: "udemy", name: "Udemy", description: "技能课程平台。", platforms: ["Web", "Android", "iOS"], tags: ["课程"] },
    { slug: "skillshare", name: "Skillshare", description: "创意与技能课程。", platforms: ["Web", "Android", "iOS"], tags: ["课程"] },
    { slug: "linkedin-learning", name: "LinkedIn Learning", description: "职业培训。", platforms: ["Web", "Android", "iOS"], tags: ["职业"] },
    { slug: "mendeley", name: "Mendeley", description: "文献管理与社交。", platforms: ["Windows", "macOS", "Linux", "Android", "iOS"], tags: ["文献"] },
    { slug: "endnote", name: "EndNote", description: "文献管理。", platforms: ["Windows", "macOS"], tags: ["文献"] },
    { slug: "readcube", name: "ReadCube", description: "论文阅读与管理。", platforms: ["Web", "Windows", "macOS", "Android", "iOS"], tags: ["文献"] },
    { slug: "remnote", name: "RemNote", description: "笔记与间隔重复。", platforms: ["Web", "Windows", "macOS", "Linux", "Android", "iOS"], tags: ["笔记"] },
    { slug: "super-memo", name: "SuperMemo", description: "间隔重复算法。", platforms: ["Windows", "Android", "iOS"], tags: ["记忆"] },
    { slug: "pleco", name: "Pleco", description: "汉语学习词典。", platforms: ["Android", "iOS"], tags: ["语言"] },
    { slug: "hello-chinese", name: "HelloChinese", description: "中文学习。", platforms: ["Android", "iOS"], tags: ["语言", "国产"] },
    { slug: "icourse163", name: "中国大学 MOOC", description: "国内高校慕课。", platforms: ["Web", "Android", "iOS"], tags: ["课程", "国产"] },
    { slug: "xuetangx", name: "学堂在线", description: "清华慕课平台。", platforms: ["Web", "Android", "iOS"], tags: ["课程", "国产"] },
    { slug: "zhihuishu", name: "智慧树", description: "高校在线课程。", platforms: ["Web", "Android", "iOS"], tags: ["课程", "国产"] },
    { slug: "study-with-me", name: "Study With Me", description: "自习与番茄钟。", platforms: ["Android", "iOS"], tags: ["效率"] },
    { slug: "forest", name: "Forest", description: "专注与种树。", platforms: ["Android", "iOS"], tags: ["专注"] },
  ],
  lifestyle: [
    { slug: "alipay", name: "支付宝", description: "支付与生活服务。", platforms: ["Android", "iOS", "Web"], tags: ["支付", "国产"] },
    { slug: "meituan", name: "美团", description: "外卖与到店。", platforms: ["Android", "iOS", "Web"], tags: ["外卖", "国产"] },
    { slug: "didi", name: "滴滴出行", description: "网约车。", platforms: ["Android", "iOS", "Web"], tags: ["出行", "国产"] },
    { slug: "amap", name: "高德地图", description: "地图导航。", platforms: ["Android", "iOS", "Web"], tags: ["地图", "国产"] },
    { slug: "baidu-maps", name: "百度地图", description: "地图与生活。", platforms: ["Android", "iOS", "Web"], tags: ["地图", "国产"] },
    { slug: "12306", name: "铁路 12306", description: "火车票购票。", platforms: ["Android", "iOS", "Web"], tags: ["出行", "国产"] },
    { slug: "ctrip", name: "携程", description: "机票酒店旅游。", platforms: ["Android", "iOS", "Web"], tags: ["旅游", "国产"] },
    { slug: "eleme", name: "饿了么", description: "外卖。", platforms: ["Android", "iOS", "Web"], tags: ["外卖", "国产"] },
    { slug: "xianyu", name: "闲鱼", description: "二手交易。", platforms: ["Android", "iOS", "Web"], tags: ["二手", "国产"] },
    { slug: "taobao", name: "淘宝", description: "电商购物。", platforms: ["Android", "iOS", "Web"], tags: ["电商", "国产"] },
    { slug: "jd", name: "京东", description: "电商与物流。", platforms: ["Android", "iOS", "Web"], tags: ["电商", "国产"] },
    { slug: "pinduoduo", name: "拼多多", description: "拼团电商。", platforms: ["Android", "iOS", "Web"], tags: ["电商", "国产"] },
    { slug: "wechat-pay", name: "微信支付", description: "腾讯支付。", platforms: ["Android", "iOS"], tags: ["支付", "国产"] },
    { slug: "uber", name: "Uber", description: "网约车与外卖。", platforms: ["Android", "iOS", "Web"], tags: ["出行"] },
    { slug: "airbnb", name: "Airbnb", description: "民宿预订。", platforms: ["Web", "Android", "iOS"], tags: ["旅游"] },
    { slug: "tripadvisor", name: "Tripadvisor", description: "旅游点评。", platforms: ["Web", "Android", "iOS"], tags: ["旅游"] },
    { slug: "yelp", name: "Yelp", description: "本地商户点评。", platforms: ["Web", "Android", "iOS"], tags: ["生活"] },
    { slug: "paypal", name: "PayPal", description: "国际支付。", platforms: ["Web", "Android", "iOS"], tags: ["支付"] },
    { slug: "revolut", name: "Revolut", description: "数字银行与支付。", platforms: ["Android", "iOS", "Web"], tags: ["支付"] },
    { slug: "dazhongdianping", name: "大众点评", description: "本地生活点评。", platforms: ["Android", "iOS", "Web"], tags: ["生活", "国产"] },
    { slug: "mafengwo", name: "马蜂窝", description: "旅游攻略。", platforms: ["Android", "iOS", "Web"], tags: ["旅游", "国产"] },
    { slug: "fliggy", name: "飞猪", description: "阿里旅行。", platforms: ["Android", "iOS", "Web"], tags: ["旅游", "国产"] },
    { slug: "tianmao", name: "天猫", description: "品牌电商。", platforms: ["Android", "iOS", "Web"], tags: ["电商", "国产"] },
    { slug: "suning", name: "苏宁易购", description: "电商与线下。", platforms: ["Android", "iOS", "Web"], tags: ["电商", "国产"] },
    { slug: "dianping", name: "点评", description: "本地生活。", platforms: ["Android", "iOS"], tags: ["生活", "国产"] },
    { slug: "meituan-waimai", name: "美团外卖", description: "外卖配送。", platforms: ["Android", "iOS"], tags: ["外卖", "国产"] },
    { slug: "shunfeng", name: "顺丰", description: "快递查询与寄件。", platforms: ["Android", "iOS", "Web"], tags: ["快递", "国产"] },
    { slug: "cainiao", name: "菜鸟", description: "阿里快递。", platforms: ["Android", "iOS"], tags: ["快递", "国产"] },
  ],
};

const CATEGORY_NAMES = {
  office: "办公软件",
  design: "设计工具",
  dev: "开发工具",
  media: "娱乐影音",
  games: "游戏",
  social: "通讯社交",
  system: "系统工具",
  education: "教育学习",
  lifestyle: "生活服务",
};

const TARGET_PER_CATEGORY = 200;

function escape(str) {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function appToTs(app, category) {
  const platforms = JSON.stringify(app.platforms);
  const tags = app.tags ? JSON.stringify(app.tags) : "undefined";
  const v = ver(
    app.name + " 最新版",
    "2024-12",
    "持续更新与优化。",
    "https://example.com/" + app.slug,
    app.platforms
  );
  const verStr = `{ version: "${escape(v.version)}", updatedAt: "${v.updatedAt}", changelog: "${escape(v.changelog)}", platforms: ${JSON.stringify(v.platforms)}, officialUrl: "${v.officialUrl}", cnMirrorUrls: ["${v.officialUrl}"] }`;
  return `  { slug: "${escape(app.slug)}", name: "${escape(app.name)}", category: "${category}", description: "${escape(app.description)}", platforms: ${platforms}, tags: ${tags}, versions: [${verStr}] }`;
}

const categories = Object.keys(SEED);
const out = [];
out.push("// 本文件由 scripts/generate-apps.js 自动生成，每类约 " + TARGET_PER_CATEGORY + " 个应用。");
out.push("// 运行 node scripts/generate-apps.js 可重新生成。");
out.push("");
out.push("export const APPS_GENERATED = [");

let total = 0;
const usedSlugs = new Set();

for (const cat of categories) {
  const seeds = SEED[cat];
  const name = CATEGORY_NAMES[cat];
  let added = 0;
  for (let i = 0; i < seeds.length; i++) {
    const app = seeds[i];
    if (usedSlugs.has(app.slug)) continue;
    usedSlugs.add(app.slug);
    out.push(appToTs({ ...app, category: cat }, cat) + ",");
    total++;
    added++;
  }
  const need = TARGET_PER_CATEGORY - added;
  for (let i = 0; i < need; i++) {
    const n = i + 1;
    const slug = `${cat}-gen-${n}`;
    if (usedSlugs.has(slug)) continue;
    usedSlugs.add(slug);
    const app = {
      slug,
      name: `${name} ${n}`,
      description: `适用于${name}场景的应用，便于分类浏览与下载。`,
      platforms: ["Windows", "macOS", "Linux"],
      tags: [name],
    };
    out.push(appToTs({ ...app, category: cat }, cat) + ",");
    total++;
  }
}

out.push("];");
out.push("");
out.push("// Total: " + total + " apps");

const filePath = path.join(__dirname, "..", "lib", "apps-generated.ts");
fs.writeFileSync(filePath, out.join("\n"), "utf8");
console.log("Wrote " + filePath + " with " + total + " apps.");
console.log("Per category target: " + TARGET_PER_CATEGORY);
